### PR TITLE
move network/database calls to IO thread

### LINKED ISSUE #65: Move network/database operations to the background/IO Thread
**Describe the bug**
>Currently, most network/database operations in the repository layer are implemented in the main/UI thread. This might lead to ANR issues due to congestion in the main thread.

**To Reproduce**
>N/A

**Expected behavior**
>All network/database operations should run in the background/IO thread so as to minimize ANR issues.

### PR DESCRIPTION
**Pull request by KennethMathari**
# Scope

_Please make sure to read https://github.com/droidconKE/droidconKE2022Android/docs/CONTRIBUTING.md
and check that you understand and have followed it as best as possible Explain what your feature
does in a short paragraph._ please check the below boxes
- [x] I have followed the coding conventions
- [x] I have added/updated necessary tests
- [x] I have tested the changes added on a physical device
- [ ] I have run `./codeAnalysis.sh` to make sure all lint/formatting checks have been done.

## Closes/Fixes Issues
fixes #65 

Please add a screenshot (if necessary)

### CODE REVIEW

File: data/src/main/java/com/android254/data/repos/AuthManager.kt [hunk 1]
```diff
@@ -23,23 +23,28 @@ import com.android254.data.network.util.TokenProvider
...
-            val result = api.googleLogin(GoogleToken(idToken))
-            tokenProvider.update(result.token)
-            DataResult.Success(Success)
-        } catch (e: Exception) {
-            when (e) {
-                is ServerError, is NetworkError -> {
-                    DataResult.Error("Login failed", networkError = true, exc = e)
-                } else -> {
-                    DataResult.Error("Login failed", exc = e)
+        return withContext(Dispatchers.IO) {
```
Comment (wangerekaharun) [inline data/src/main/java/com/android254/data/repos/AuthManager.kt:35]: It is recommended you inject dispatchers using DI instead of hardcoded ones: Read here:[ ](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers)

**Review by wangerekaharun — COMMENTED** [review]
Looks Good left a comment

**Comment by yveskalume** [comment]
@KennethMathari you can use that as your guide if you want 
https://github.com/yveskalume/gif-app/tree/main/data/src/main/java/com/yvkalume/gifapp/data

**Comment by KennethMathari** [comment]
> @KennethMathari to inject Dispatcher with hilt, you can use that as your guide if you want. https://github.com/yveskalume/gif-app/tree/main/data/src/main/java/com/yvkalume/gifapp/data

Thanks for this. I'll check it out

**Comment by KennethMathari** [comment]
@wangerekaharun I've made the changes. PR is now ready for review

File: data/src/main/java/com/android254/data/repos/HomeRepoImpl.kt [hunk 2]
```diff
@@ -27,29 +28,36 @@ import com.android254.domain.models.Session
...
+
 class HomeRepoImpl @Inject constructor(
     private val sponsorsApi: SponsorsApi,
     private val speakersRepo: SpeakersRepo,
     private val sessionsRepo: SessionsRepo,
+    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
 ) : HomeRepo {
     @RequiresApi(Build.VERSION_CODES.O)
     override suspend fun fetchHomeDetails(): HomeDetails {
         val sponsors = sponsorsApi.fetchSponsors()
```
Comment (wangerekaharun) [inline data/src/main/java/com/android254/data/repos/HomeRepoImpl.kt:45]: should this be in `withContext` as well?

**Comment by wangerekaharun** [comment]
@KennethMathari CI is failing, kindly check

**Review by michaelbukachi — APPROVED** [review]
