### PR TITLE
About dark

### LINKED ISSUE #137: [Fix About Us] Text colour not clear in dark mode
**Describe the bug**
Some of the text in the about screen is not visible in dark theme mode

**To Reproduce**
1. Change device settings to dark theme before opening the app 
2. Go to 'About'
3. See unreadable sections in screen

**Expected behavior**
Readable text

**Screenshots**
Added screenshot
Screenshot_20230614-222208

### PR DESCRIPTION
**Pull request by Borwe**
# Scope
Fix color issues on About Us page from issue #137 and also the feedback text color on the topbar.

_Please make sure to read the [Contribution Guidelines](https://github.com/droidconKE/droidconKE2023Android/blob/main/CONTRIBUTING.md)
and check that you understand and have followed it as best as possible Explain what your feature
does in a short paragraph._ please check the below boxes
- [x] I have followed the coding conventions
- [x] I have added/updated necessary tests
- [x] I have tested the changes added on a physical device
- [x] I have run `./codeAnalysis.sh` on linux/unix or `codeAnalysys.bat` on windows to make sure all lint/formatting checks have been done.

## Closes/Fixes Issues
Fixes #137 

## Other testing QA Notes
Dark mode.

Please add a screenshot (if necessary)
How it currently looks after fix...
about_dark
about_dark2

### CODE REVIEW

File: presentation/src/main/java/com/android254/presentation/about/view/AboutScreen.kt [hunk 1]
```diff
@@ -175,7 +178,7 @@ fun OrganizingTeamSection(
             modifier = Modifier.fillMaxWidth(),
             text = stringResource(id = R.string.about_organizing_team),
             style = TextStyle(
-                color = ChaiBlue,
+                color = if (!isSystemInDarkTheme()) ChaiBlue else ChaiTeal,
```
Comment (MamboBryan) [inline presentation/src/main/java/com/android254/presentation/about/view/AboutScreen.kt:181]: We shouldn't check if the system is in darkMode here, we can use `MaterialTheme.colorScheme` and pick the relevant colour needed that matches the design in both `Light` and `Dark` mode.
They can be found here : [Theme Colors ](https://github.com/droidconKE/droidconKE2023Android/blob/main/chai/src/main/java/com/droidconke/chai/Theme.kt)

> Please Note  
If you have looked at the design and confirmed there is no matching color you can create it and  :
- create a color variable using the example set for `textColorPrimary` found [here](https://github.com/droidconKE/droidconKE2023Android/blob/main/chai/src/main/java/com/droidconke/chai/colors/ChaiColors.kt)
- call your color variable from the composable using `MaterialTheme.chaiColorsPalette.{yourColorName}`

File: presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt [hunk 2]
```diff
@@ -49,7 +52,7 @@ fun OrganizedBySection(
         modifier = modifier
             .fillMaxWidth()
             .background(
-                color = ChaiLightGrey,
+                color = if (!isSystemInDarkTheme()) ChaiLightGrey else ChaiBlack,
```
Comment (MamboBryan) [inline presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt:55]: We shouldn't check if the system is in darkMode here, we can use `MaterialTheme.colorScheme` and pick the relevant colour needed that matches the design in both `Light` and `Dark` mode.
They can be found here : [Theme Colors ](https://github.com/droidconKE/droidconKE2023Android/blob/main/chai/src/main/java/com/droidconke/chai/Theme.kt)

> Please Note  
If you have looked at the design and confirmed there is no matching color you can create it and  :
- create a color variable using the example set for `textColorPrimary` found [here](https://github.com/droidconKE/droidconKE2023Android/blob/main/chai/src/main/java/com/droidconke/chai/colors/ChaiColors.kt)
- call your color variable from the composable using `MaterialTheme.chaiColorsPalette.{yourColorName}`

File: presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt [hunk 3]
```diff
@@ -59,7 +62,7 @@ fun OrganizedBySection(
             modifier = Modifier.fillMaxWidth(),
             text = stringResource(id = R.string.organized_by),
             style = TextStyle(
-                color = ChaiBlue,
+                color = if (!isSystemInDarkTheme()) ChaiBlue else ChaiTeal,
```
Comment (MamboBryan) [inline presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt:65]: We shouldn't check if the system is in darkMode here, we can use `MaterialTheme.colorScheme` and pick the relevant colour needed that matches the design in both `Light` and `Dark` mode.
They can be found here : [Theme Colors ](https://github.com/droidconKE/droidconKE2023Android/blob/main/chai/src/main/java/com/droidconke/chai/Theme.kt)

> Please Note  
If you have looked at the design and confirmed there is no matching color you can create it and  :
- create a color variable using the example set for `textColorPrimary` found [here](https://github.com/droidconKE/droidconKE2023Android/blob/main/chai/src/main/java/com/droidconke/chai/colors/ChaiColors.kt)
- call your color variable from the composable using `MaterialTheme.chaiColorsPalette.{yourColorName}`

**Review by MamboBryan — CHANGES_REQUESTED** [review]

**Comment by Borwe** [comment]
Updaed to use MaterialTeme.colorScheme as requested, added a little tint to the `md_theme_light_surfaceTint` in Colors.kt to a darker blue, as it was the only combo with a teal version in dark mode.

Final look:
Dark
about_dark
about_dark2

Light
about_light
about_light2

File: presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt [hunk 4]
```diff
@@ -49,7 +53,7 @@ fun OrganizedBySection(
         modifier = modifier
             .fillMaxWidth()
             .background(
-                color = ChaiLightGrey,
+                color = MaterialTheme.colorScheme.surface,
```
Comment (wangerekaharun) [inline presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt:56]: @Borwe why are you moving away from colors of our design system

Comment (Borwe) [reply presentation/src/main/java/com/android254/presentation/common/components/OrganizedBySection.kt:56]: I thought I was supposed to move to MaterialTheme.colorScheme.X so that dark and light mode we wouldn't have to use if statements to check according to this request:

https://github.com/droidconKE/droidconKE2023Android/pull/140#discussion_r1230950559

**Review by MamboBryan — APPROVED** [review]

**Review by misshannah — APPROVED** [review]
Trusting @MamboBryan in testing this 👍
